comment_width = 100
imports_granularity = "Module"
imports_layout = "Horizontal"
force_multiline_blocks = true
format_code_in_doc_comments = true
max_width = 100
normalize_comments = true
reorder_impl_items = true
use_small_heuristics = "Max"
tab_spaces = 2
wrap_comments = true
